language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        # Debug in next line: " && cat .env"
        script: npx semantic-release && cat .env
        on:
          all_branches: true
